sudo: required
services:
  - docker

before_install:
  - docker build -t kh94/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kh94/react-test npm test -- --coverage

# Build using the production dockerfiles
after_success:
  - docker build -t kh94/multi-client ./client
  - docker build -t kh94/multi-nginx ./nginx
  - docker build -t kh94/multi-server ./server
  - docker build -t kh94/multi-worker ./worker

  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push kh94/multi-client
  - docker push kh94/multi-nginx
  - docker push kh94/multi-server
  - docker push kh94/multi-worker
